// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4GNZL53hAZA7N8WUYPa5PbCxfUtHknY',
    appId: '1:103200839872:web:de38bacddfb3cab8c47525',
    messagingSenderId: '103200839872',
    projectId: 'food-delivery-app-3202c',
    authDomain: 'food-delivery-app-3202c.firebaseapp.com',
    storageBucket: 'food-delivery-app-3202c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTuCg-0iMqSrHtTS239-C234hB5rBQspY',
    appId: '1:103200839872:android:0106d05f6e6a6d51c47525',
    messagingSenderId: '103200839872',
    projectId: 'food-delivery-app-3202c',
    storageBucket: 'food-delivery-app-3202c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBow-9ba6XqjhB23ksBMuOF14tQMv_u4w0',
    appId: '1:103200839872:ios:c1b72b49aad93fafc47525',
    messagingSenderId: '103200839872',
    projectId: 'food-delivery-app-3202c',
    storageBucket: 'food-delivery-app-3202c.firebasestorage.app',
    iosBundleId: 'com.tanmay.foodDeliveryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBow-9ba6XqjhB23ksBMuOF14tQMv_u4w0',
    appId: '1:103200839872:ios:c1b72b49aad93fafc47525',
    messagingSenderId: '103200839872',
    projectId: 'food-delivery-app-3202c',
    storageBucket: 'food-delivery-app-3202c.firebasestorage.app',
    iosBundleId: 'com.tanmay.foodDeliveryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo4GNZL53hAZA7N8WUYPa5PbCxfUtHknY',
    appId: '1:103200839872:web:99390db924b0ab85c47525',
    messagingSenderId: '103200839872',
    projectId: 'food-delivery-app-3202c',
    authDomain: 'food-delivery-app-3202c.firebaseapp.com',
    storageBucket: 'food-delivery-app-3202c.firebasestorage.app',
  );
}
